version: '3.9'

services:
  mysql:
    image: mysql:8.0.30
    ports:
      - 33061:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=user
      - MYSQL_USER=user
      - MYSQL_DATABASE=pnsb
